### ISSUE TITLE
move yaml files into /config

### ISSUE THREAD

**Issue by esheldon** [sweverett/Balrog-GalSim#1]
There is a directory config where we can put example config files (see `config/balrog-test01.yaml` which is an example full balrog config)

We can move e.g. `single_epoch.yaml` there

**Comment by amichoi** [comment]
I'll do that in the next commit.

**Comment by sweverett** [comment]
Cleaning up the repo - we currently have `ngmix_test.yaml` and `bal_config.yaml` in the `/config` dir which explain how to use the GalSim input `ngmix_catalog` and a full Balrog test run respectively.
