### ISSUE TITLE
Call to os.environ['BALROG_DIR'] not recognized in single_epoch.yaml

### ISSUE THREAD

**Issue by amichoi** [sweverett/Balrog-GalSim#3]
To get `galsim single_epoch.yaml` to work, one needs to replace the call to `os.environ['BALROG_DIR'] `with the full path to BALROG_DIR instead.  Might need an `import os` somewhere?

**Comment by amichoi** [comment]
Here's the traceback.  If I instead use - &BALROG_DIR /Users/amichoi/src/Balrog-GalSim everything runs fine.

Amis-MacBook-Pro:config amichoi$ echo $BALROG_DIR
/Users/amichoi/src/Balrog-GalSim
Amis-MacBook-Pro:config amichoi$ galsim single_epoch.yaml
Using config file single_epoch.yaml
Warning: config dict contains the following unexpected fields: ['some_variables', 'bright_gal', 'faint_gal', 'nearby_gal', 'star'].
These fields are not (directly) processed by the config processing.
Traceback (most recent call last):
  File "/usr/local/bin/galsim", line 275, in <module>
    main()
  File "/usr/local/bin/galsim", line 256, in main
    except_abort=args.except_abort)
  File "/Users/amichoi/anaconda/lib/python2.7/galsim/config/process.py", line 780, in Process
    except_abort=except_abort)
  File "/Users/amichoi/anaconda/lib/python2.7/galsim/config/output.py", line 104, in BuildFiles
    file_name = valid_output_types[output_type].getFilename(output, config, logger)
  File "/Users/amichoi/anaconda/lib/python2.7/site-packages/galsim_extra/focal_plane.py", line 225, in getFilename
    return super(FocalPlaneBuilder, self).getFilename(config, base, logger)
  File "/Users/amichoi/anaconda/lib/python2.7/galsim/config/output.py", line 435, in getFilename
    file_name = galsim.config.ParseValue(config, 'file_name', base, str)[0]
  File "/Users/amichoi/anaconda/lib/python2.7/galsim/config/value.py", line 104, in ParseValue
    val_safe = generate_func(param, base, value_type)
  File "/Users/amichoi/anaconda/lib/python2.7/galsim/config/value.py", line 629, in _GenerateFromFormattedStr
    val, safe1 = ParseValue(items, index, base, val_types[index])
  File "/Users/amichoi/anaconda/lib/python2.7/galsim/config/value.py", line 104, in ParseValue
    val_safe = generate_func(param, base, value_type)
  File "/Users/amichoi/anaconda/lib/python2.7/galsim/config/input.py", line 426, in _GenerateFromCatalog
    galsim.config.SetDefaultIndex(config, input_cat.getNObjects())
AttributeError: 'NoneType' object has no attribute 'getNObjects'

**Comment by esheldon** [comment]
Why is that directory needed?  Is it trying to read some file distributed with the code?

It is not usual to need to know where a code was installed *from*, but one might need to know where it was installed *to*. Was  the code installed with setup.py?  Was the needed data file not installed?

**Comment by amichoi** [comment]
It's being used to specify inputs.  I did install with setup.py, and the necessary data file wasn't installed -- but since these input data files will change often (i.e. input DES tiles), I thought it would be better to pass a variable directory to look in.

**Comment by esheldon** [comment]
I see what you are doing now.   I have used that trick with os.environ before, I'm surprised it didn't work.  What version of galsim are you using?  I think you might need the latest.

**Comment by amichoi** [comment]
I kind of copied the idea from your nbrsim config actually.  =) I thought I had the latest version of GalSim (GalSim Version 1.5 is returned by galsim --version).  Just did a git pull and scons install to make sure.

**Comment by emhuff** [comment]
I had a similar problem, and installed 1.5.0-alpha installed.

Eric

**Comment by sweverett** [comment]
Cleaning the repo - no longer relevant. See `config/ngmix_test.yaml` and `config/bal_test.yaml` for examples of how to set `BALROG_DIR` (actually set as `BAL_DIR` for now)
