### ISSUE TITLE
DESDM stack first pass

### ISSUE THREAD

**Issue by NiallMac** [sweverett/Balrog-GalSim#4]
Let's try and get a simple script that runs:
i) Downloading necessary input images (desmeds prep tile command)
ii) Galsim (can start with a dummy Galsim run i.e. just copy the SE images to a different directory iii) Swarp
iv) SExtractor light - some comparison of resulting SExtractor catalogs to the DESDM ones would be good here.

(Once step iv) looks ok, move on to making meds files and running MOF)

**Comment by sweverett** [comment]
All tasks completed for 3 test tiles
